### ISSUE TITLE
 NodeRED/Benachrichtigung, wenn die Waschmaschine fertig ist / Code nicht komplett

### ISSUE THREAD

**Issue by vore** [CoHoB/NodeRED#1]
Hello!
Danke für dein hilfreiches Beispiel! Allerdings scheint der Code nicht komplett zu sein. Beim Import in Node Red kommt eine Fehlermeldung. Kannst Du den kompletten Export posten?
Danke!
Gruß
Volker

**Comment by CoHoB** [comment]
Hallo Volker,

danke für den Hinweis.
Das ist beim Umkodieren von utf8 nach latin1 verloren gegangen, weil in den Benachrichtigungstexten einige Sonderzeichen enthalten waren, die es im ISO-Zeichensatz nicht gibt und zum stillschweigenden Abbruch der Konvertierung geführt haben. Der Flow ist nun wieder im Ganzen enthalten.
Falls Du Homematic IP-Aktoren einsetzt, empfehle ich Dir auch den Beitrag mit dem Entscheidungswert anzusehen - damit wird der Duty Cycle massiv reduziert und funktioniert bei mir seit knapp einem Jahr sehr gut.

Viele Grüße und schöne Feiertage
André

**Comment by vore** [comment]
Hallo Andre,
Ok, Danke für den Hinweis und die schnelle Anpassung des Flows. Ich nutze dem HM-IP Messaktor, daher sehe ich mir dann noch mal den anderen Beitrag an. 
Gruß
Volker
